### ISSUE TITLE
ValueError: NodeDef mentions attr 'feature_win_len' not in Op

### ISSUE THREAD

**Issue by wangdayan** [TimoBolkart/voca#10]
Hi, 

thanks for sharing! 

I am currently trying to run your code on my machine(Python 2.7& Tensorflow 1.12.0).
When I run command line "python run_voca.py", there are some problems, The following is the output, is there something wrong with my settings?

Thank you so much!!!

<
$ python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/FLAME_sample.ply' --condition_idx 3 --out_path './animation_output'
Traceback (most recent call last):
  File "run_voca.py", line 44, in <module>
    inference(tf_model_fname, ds_fname, audio_fname, template_fname, condition_idx, out_path)
  File "/home/wangqianyun/voca/utils/inference.py", line 62, in inference
    processed_audio = process_audio(ds_fname, audio, sample_rate)
  File "/home/wangqianyun/voca/utils/inference.py", line 41, in process_audio
    return audio_handler.process(tmp_audio)['subj']['seq']['audio']
  File "/home/wangqianyun/voca/utils/audio_handler.py", line 53, in process
    return self.convert_to_deepspeech(audio)
  File "/home/wangqianyun/voca/utils/audio_handler.py", line 101, in convert_to_deepspeech
    tf.import_graph_def(graph_def, name="deepspeech")
  File "/home/wangqianyun/voca/voca/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/wangqianyun/voca/voca/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'feature_win_len' not in Op<name=NoOp; signature= -> >; NodeDef: {{node deepspeech/model_metadata}} = NoOp[feature_win_len=32, feature_win_step=20, sample_rate=16000](). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
>

**Comment by TimoBolkart** [comment]
Hi, 

can you please provide some more information about your setup? Did you download the trained DeepSpeech model (v0.1.0) from Mozilla/DeepSpeech (i.e. deepspeech-0.1.0-models.tar.gz)?

**Comment by wangdayan** [comment]
Hi,

thank you for your reply!
Yes, I downloaded deepspeech-0.5.0-models. Does the version affect the results? I will try 0.1.0 later!

**Comment by TimoBolkart** [comment]
Hi,

yes, the downloaded version matters as Mozilla changed some things in how to handle the input data. Please try with v0.1.0 and let me know if this fixes the problem.

**Comment by wangdayan** [comment]
Hi,

thank you so much(≧∇≦)ﾉ v0.1.0 fixes this problem perfectly!
