### ISSUE TITLE
 Unknown mesh file format.

### ISSUE THREAD

**Issue by Langwenchong** [TimoBolkart/voca#117]
D:\Pythoncode\voca-master>python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/FLAME_sample.ply' --condition_idx 3 --out_path './animation_output' Traceback (most recent call last): File "run_voca.py", line 59, in <module> inference(tf_model_fname, ds_fname, audio_fname, template_fname, condition_idx, out_path, str2bool(args.visualize), uv_template_fname=uv_template_fname, texture_img_fname=texture_img_fname) File "D:\Pythoncode\voca-master\utils\inference.py", line 102, in inference template = Mesh(filename=template_fname) File "D:\Python\anaconda3\envs\FaceFormer\lib\site-packages\psbody\mesh\mesh.py", line 67, in __init__ self.load_from_file(filename) File "D:\Python\anaconda3\envs\FaceFormer\lib\site-packages\psbody\mesh\mesh.py", line 461, in load_from_file serialization.load_from_file(self, filename) File "D:\Python\anaconda3\envs\FaceFormer\lib\site-packages\psbody\mesh\serialization\serialization.py", line 423, in load_from_file raise NotImplementedError("Unknown mesh file format.") NotImplementedError: Unknown mesh file format.

Hello, I want to try to run demo, but the model format error was reported after inputting instructions. Could you please kindly ask me how to solve it? Thank you very much！

**Comment by Langwenchong** [comment]
I've already fixed this problem, probably because of a version issue I ended up just removing the double quotes that contained the path, if you have this problem you can try doing the same as me.
