### ISSUE TITLE
dataset/voca_face_former/templates.pkl not found

### ISSUE THREAD

**Issue by ShrDama** [TimoBolkart/voca#124]
The dataset provided in the link only has data_verts.npy. Thus it's throwing an error.

Running on GPUs 0,
Loading data...
Using global processor to process the model
Traceback (most recent call last):
  File "/Users/S.Dama/Downloads/Imitator-main/main.py", line 311, in <module>
    data = instantiate_from_config(config.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/S.Dama/Downloads/Imitator-main/main.py", line 118, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/S.Dama/Downloads/Imitator-main/imitator/data/debug_data_loader.py", line 149, in __init__
    train_data, valid_data, test_data, subjects_dict = read_data(**kwargs)
                                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/S.Dama/Downloads/Imitator-main/imitator/data/debug_data_loader.py", line 76, in read_data
    with open(template_file, 'rb') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/projects/dataset/voca_face_former/templates.pkl'

**Comment by TimoBolkart** [comment]
Hello, can you please specify what you are running? The file path hints at something related to Imitator, and voca_face_former is nothing that is distributed with the VOCA repository. Did you follow the installation in this VOCA repository and tried to run the official VOCA demo?
