### ISSUE TITLE
tensorflow-gpu 1.14.0 error importing

### ISSUE THREAD

**Issue by jdchanggg** [TimoBolkart/voca#23]
When I try to import tensorflow-gpu 1.14.0 with `pip install -r requirements.txt`, I get the following error. How do I deal with this? Can I just use pip install tensorflow-gpu 1.14.0 instead and it will work?

(voca) josephdanielchang@ubuntu:~/voca$ pip install -r requirements.txt
Collecting numpy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl (20.0MB)
    100% |████████████████████████████████| 20.0MB 102kB/s 
Collecting scipy (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/54/18/d7c101d5e93b6c78dc206fcdf7bd04c1f8138a7b1a93578158fa3b132b08/scipy-1.3.3-cp36-cp36m-manylinux1_x86_64.whl (25.2MB)
    100% |████████████████████████████████| 25.2MB 78kB/s 
Collecting chumpy (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/87/81/d7a94ad0ff556b9dd1bf27b84c0b255d9ba22ad5952f20088dafacd9292e/chumpy-0.69.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 2.5MB/s 
Collecting opencv-python (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/c0/a9/9828dfaf93f40e190ebfb292141df6b7ea1a2d57b46263e757f52be8589f/opencv_python-4.1.2.30-cp36-cp36m-manylinux1_x86_64.whl (28.3MB)
    100% |████████████████████████████████| 28.3MB 65kB/s 
Collecting resampy (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/79/75/e22272b9c2185fc8f3af6ce37229708b45e8b855fd4bc38b4d6b040fff65/resampy-0.2.2.tar.gz (323kB)
    100% |████████████████████████████████| 327kB 3.2MB/s 
Collecting python-speech-features (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ff/d1/94c59e20a2631985fbd2124c45177abaa9e0a4eee8ba8a305aa26fc02a8e/python_speech_features-0.6.tar.gz
Collecting tensorflow-gpu==1.14.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/76/04/43153bfdfcf6c9a4c38ecdb971ca9a75b9a791bb69a764d652c359aca504/tensorflow_gpu-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (377.0MB)
    99% |████████████████████████████████| 377.0MB 14.6MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/josephdanielchang/.virtualenvs/voca/lib/python3.6/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/josephdanielchang/.virtualenvs/voca/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

**Comment by TimoBolkart** [comment]
Sure, you can just try to install TF manually within the virtual environment using pip install. Some of the requirements might still be missing, but you can afterwards also just manually install them. Please let me know if this works

**Comment by jdchanggg** [comment]
Thanks for such a fast response. I ran into a lot of errors and exceptions, but I finally got everything to run
