### ISSUE TITLE
OpenGL Error while imported the main file from another

### ISSUE THREAD

**Issue by 12345data** [TimoBolkart/voca#62]
I have changed the main file(run_voca.py) code for reading the parameters like template and audio file directly from the disk. This was running fine. But I have imported this file to a flask server for creating it as a service. But when I called the main function it is giving the following error. 
`Traceback (most recent call last):
  File "/home/user-name/Documents/3DAvatar/avatar_server.py", line 6, in <module>
    import main_voca as voca
  File "/home/user-name/Documents/3DAvatar/main_voca.py", line 15, in <module>
    from utils.inference import inference
  File "/home/user-name/Documents/3DAvatar/utils/inference.py", line 13, in <module>
    from psbody.mesh import Mesh
  File "/home/user-name/Documents/3DAvatar/env/lib/python3.6/site-packages/psbody/mesh/__init__.py", line 10, in <module>
    from .meshviewer import MeshViewer, MeshViewers
  File "/home/user-name/Documents/3DAvatar/env/lib/python3.6/site-packages/psbody/mesh/meshviewer.py", line 49, in <module>
    from OpenGL import GL, GLU, GLUT
  File "/home/user-name/Documents/3DAvatar/env/lib/python3.6/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
    from OpenGL.GLUT.fonts import *
  File "/home/user-name/Documents/3DAvatar/env/lib/python3.6/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
    p = platform.getGLUTFontPointer( name )
  File "/home/user-name/Documents/3DAvatar/env/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 345, in getGLUTFontPointer
    """Platform does not define a GLUT font retrieval function""" 
NotImplementedError: Platform does not define a GLUT font retrieval function`
Both the files(flask-server file and the main file) are placed in same location. Direct running of the main file is successful but importing the same and running the function causes the issue. 
Can anyone help me how this issue is caused and how can I solve this?

**Comment by AndrewMorgan2** [comment]
Did you ever solve this?
